version: '3'
services:
  app:
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app

  
  postgres:
    image: postgres:latest
    container_name: to-do-list-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: to-do-list
      POSTGRES_USER: glaymar2010@gmail.com
      POSTGRES_PASSWORD: nada



